blog/urls.py
from django.urls import path

# from . import views
from .views import (
				PostList,
				DoList,
				DetailPost,
				error_404,
				error_500,
				search_post

	)
from django.conf.urls import handler404, handler500



app_name = "post"
urlpatterns = [
	path('', PostList.as_view(), name='post-list'),
	path('<slug:slug>/', DetailPost.as_view(), name='detail_post'),
	path('category/<name>', DoList.as_view(), name='category'),
    path('search', search_post, name='search')

]
handler404 = error_404
handler500 = error_500

blogger/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('blog.urls', namespace='posts'))
]
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	

templates/base.html
{% load staticfiles %}
{% load social_widgets %}

<!doctype html>
<html lang="ar">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        
    <title >{% block head_title %}جــانــجــو عـربـي{% endblock head_title%}</title>
<!--     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
     <link href="https://fonts.googleapis.com/css?family=Tajawal&display=swap" rel="stylesheet">

   <link rel="stylesheet" href="{% static 'ispan/css/bootstrap.min.css' %}">
   <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

   <link rel="stylesheet" type="text/css" href='{% static "css/style.css" %}'>

</head>

<body>


    <!-- Header -->
{% include "header.html" %}
 

{% block content %}
{% endblock content %}  


<!-- Footer -->   
  <footer id="footer" class="py-5  mt-4 bg-grey" style="background-color: #f5f5f5;">
      <!-- container -->
      <div class="container">
        <!-- row -->
        <div class="row">
         
          <div class="col-md-3">
            <div class="mb-5 footer-nav">
              
              <div class="mb-5">
                <a class="navbar-brand" href="{% url 'posts:post-list' %}">جــانــجــو 
                  <span class="blou-logo">عـربـي</span>
                </a> 
              </div>

              <ul class="nav">
                <li class="ml-4"><a href="#">link</a></li>
                <li class="ml-4"><a href="#">link</a></li>
              </ul>

              <div class="mt-4 foo-copy">
                <span>
                  Copyright &copy;
                   by Radi Obad
                </span>
              </div>

            </div>
          </div>

          <div class="col-md-5">
            <div class="row">
              <div class="col-md-6">
                <div class="mb-5 footer-nav">
                  <h3 class="mb-5">من نحن</h3>
                  <ul>
                    <li><a href="index.html">الرئيسية</a></li>
                    <li><a href="about.html">من نحن</a></li>
                    <li><a href="#">تواصل معنا</a></li>
                  </ul>
                </div>
              </div>

            <div class="col-md-6">
                <div class="mb-5 footer-nav">
                  <h3 class="mb-5">العناوين</h3>
                  <ul>
                    {% for menu in menu %}
                            <li class=""><a href="{% url 'posts:category' menu.menu %}" class="">{{ menu.menu }}</a></li>
                     {% endfor %}       
                  </ul>
                </div>
              </div>

            </div>
          </div>

          <div class="col-md-4">
            <div class="mb-5">
              <h3 class="mb-5"> أشترك معنا وتابعنا </h3>
              <div class="foo-sub">
                <form>
                  <input type="email" name="newssub" class="input" placeholder="Enter your email">
                  <button class="newssub-btn"> <i class="fa fa-paper-plane"></i></button>
                </form>
              </div>
                <ul class="footer-social mt-4 nav" style="padding-right: 0">
                <li class="ml-3"><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li class="ml-3"><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li class="ml-3"><a href="#"><i class="fa fa-google-plus"></i></a></li>
                <li class="ml-3"><a href="#"><i class="fa fa-pinterest"></i></a></li>
              </ul>

            </div>
          </div>
      </div>
    </div>
    <!-- /row -->
  </div>
    <!-- /container -->
</footer>

<!-- /footer -->




<!-- <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
 -->
  <script src="{% static 'ispan/js/jquery-3.3.1.min.js' %}"></script>

 <script src="{% static 'ispan/js/popper.min.js' %}"></script>

 <script src="{% static 'ispan/js/bootstrap.min.js' %}"></script>
 <script src="{% static 'js/main.js' %}"></script>

<!-- <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
 -->
 {%block script%}
 {%endblock%}
</body>
</html>

templates/category.html
{% extends "base.html" %}
{% load static %}
{% load urlify %}

{% block head_title %}
  	{{block.super}} | {{title}} 
{% endblock head_title %}
{% block content %}


<!-- Page Content -->
 <section class="site-section py-5">
      <div class="container">
             <!-- Page Heading -->
           <!--  <h1 class="">قائمة الدروس
            </h1> -->
          <div class="row">
            <div class="col-md-12 col-lg-10">
              {%for bom in posts%}
                <div class="row mb-3">
                  <div class="col-md-5 col-lg-5">
                      {% if bom.category %}
                      {% endif %}
                      <div href="#" class="post-thumb">
                        <h5 class="post-cat-wrap">
                          <span class="post-cat text-white bg-primary">{{ bom.category |upper }}</span>
                        </h5>
                        <div class="post-thumb-overlay-wrap">
                            <img class="img-fluid rounded mb-3 mb-md-0" src="{{bom.referential_image.url}}" alt="">
                        </div>
                      </div>

                  </div>
                  <div class="col-md-7 col-lg-7">
                      <h3>{{ bom.title }}</h3>
                      <p>{{ bom.description|slice:":100" }} ...</p>
                      <a class="btn btn-primary more-link" style="hover:border: none !important;" href="{% url 'posts:detail_post' bom.slug %}">المزيد !!</a>
                  </div>
                </div>
            {% endfor %}
            <!-- /.row -->
      

      </div>
    </div>
  </div>
</section>



{% endblock content %}

templates/header.html
 <header id="header">
    <!-- Nav -->
    <nav id="nav">
        <!-- Main Nav -->
        <div id="nav-fixed">

         <nav class="navbar navbar-expand-lg main-nav sticky-top navbar-light bg-light menu-wrapper" id=" mainNav" style="background-color: #fff !important;">
              <div class="container">
                  <a class="navbar-brand" href="{% url 'posts:post-list' %}">جــانــجــو <span class="blou-logo">عـربـي</span>
                  </a>
                 
                  <div class="collapse navbar-collapse" id="navbarResponsive">
                      <ul class="navbar-nav nav-menu ml-auto">

                          {% for menu in menu %}
                            <li class="nav-item cat-{{ forloop.counter }} text-black"><a href="{% url 'posts:category' menu.menu %}" class="nav-link text-black font-weight-bold">{{ menu.menu }}</a></li>
                          {% endfor %}
                      </ul>
                  </div>
                  
                  <!-- search & aside toggle -->
                      <div class="nav-btns">
                          <button class="aside-btn"><i class="fa fa-bars"></i></button>
                          <button class="search-btn"><i class="fa fa-search"></i></button>
                           <form class="search-form" method="POST" action="{% url 'posts:search' %}">
                              {% csrf_token %}
                              <div class="search-form">
                                  <input class="search-input" type="text" name="search" placeholder="Enter Your Search ...">
                                  <button class="search-close"><i class="fa fa-times"></i></button>
                              </div>                        
                            </form>
                      </div>
                      <!-- /search & aside toggle -->
              </div>
          </nav>
         </div>
        <!-- Aside Nav -->
                <div id="nav-aside">
                    <!-- nav -->
                    <div class="section-row">
                        <ul class="nav-aside-menu">
                            <li><a href="{% url 'posts:post-list' %}">الرئيسية</a></li>
                            <li><a href="#">من نحن</a></li>
                            <li><a href="#">تواصل معنا</a></li>
                        </ul>
                    </div>
                    <!-- /nav -->
                     <!-- nav -->
                    <div class="section-row sooooo">
                        <ul class="nav-aside-menu">
                            <li><a href="">الجديدة</a></li>
                            <li><a href="">المستقبلية</a></li>
                            {% for menu in menu %}
                            <li><a href="{% url 'posts:category' menu.menu %}">{{ menu.menu }}</a></li>
                            {% endfor %}
                            
                        </ul>
                    </div>
                    <!-- /nav -->

                    <!-- widget posts -->
                    <div class="section-row">
                        <h3>Recent Posts</h3>
                        {%  for post in recent_post%}
                        <div class="post post-widget">
                            <a class="post-img" href="{{post.get_absolute_url}}">
                              <img src="{{post.referential_image.url}}" alt="">
                            </a>
                            <div class="post-body">
                                <h3 class="post-title"><a href="{{post.get_absolute_url}}">{{post.title}}</a></h3>
                            </div>
                        </div>
                        {% endfor %}

                     

                    </div>
                    <!-- /widget posts -->

                    <!-- social links -->
                    <div class="section-row">
                        <h3>Follow us</h3>
                        <ul class="nav-aside-social">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                        </ul>
                    </div>
                    <!-- /social links -->

                    <!-- aside nav close -->
                    <button class="nav-aside-close"><i class="fa fa-times"></i></button>
                    <!-- /aside nav close -->
                </div>
        <!-- /Aside Nav -->

    </nav>
  </header>

templates/index.html
{% extends "base.html" %} 
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }
    
    .head_text {
        color: white;
    }
    
    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my awesome Blog </h3>
                    <p class="text-light">We Love Django As much as you do..! &nbsp
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container mt-3">
    
        <!-- Blog Entries Column -->
        <form method="GET" action="">
        	<input type="text"  name="q" placeholder="Search post" value="{{ request.GET.q }}">
        	<input type="submit" name="" value="Searsh">
        </form>

</div>

<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
     
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    {% if post.draft %}
                    <small style="color: red">
                    	staff only: Draft: 
                    </small>
                    {% if post.publish > today  %} 

                    <small style="color: red">
                    	staff only: future post
                    </small>
                    {% endif %}
                    {% endif %}
                    <p class="card-text text-muted h6"><small>{{ post.updated|timesince}} ago</small></p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{{  post.get_absolute_url}}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
        {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
    </div>
</div>
{%endblock%}

templates/pagination.html
<div class="pt-3 mt-4 mb-5 text-center">
    {% if page.has_next %}
    <a class="btn btn-secondary bg-secondary" href="?page={{page.next_page_number}}">التالي</a>
    {% else %}
    <a class="btn btn-secondary bg-secondary disabled" href="#">التالي</a>
    {% endif %}

    <span class="pr-4 pl-4">صفحة {{page.number}} من {{page.paginator.num_pages}}</span>

    {% if page.has_previous %}
    <a class="btn btn-secondary bg-secondary" href="?page={{page.previous_page_number}}">السابق</a>
    {% else %}
    <a class="btn btn-secondary bg-secondary disabled" href="#">السابق</a>
    {% endif %}
</div>

templates/post_detail.html
{% extends "base.html" %}
{% load static %}
{% load urlify %}

{% block head_title %}
 {{block.super}} | {{title}}
{% endblock head_title %}
{% block content %}
<style type="text/css">
	.post.post-thumb {
    position: relative;
}
.post .post-img {
    display: block;
    -webkit-transition: 0.2s opacity;
    transition: 0.2s opacity;
}
.post .post-img > img {
    width: 100%;
}
.post.post-thumb .post-img::after {
    content: '';
    position: absolute;
    left: 0;
    right: 0;
    bottom: 0;
    top: 0;
    background: -webkit-gradient(linear, left bottom, left top, from(rgba(33, 38, 49, 0.3)), to(transparent));
    background: linear-gradient(to top, rgba(33, 38, 49, 0.3) 0%, transparent 100%);
}
.post.post-thumb .post-body {
    position: absolute;
    bottom: 0px;
    padding: 20px 15px;
}
.post .post-meta {
    margin-top: 15px;
    margin-bottom: 15px;
    display: inline-block;
}
.post-meta .post-category.cat-2 {
    background-color: #ff8700;
}
.post-meta .post-category.cat-3 {
    background-color: #8d00ff;
}
.post-meta .post-category {
    font-size: 13px;
    text-transform: uppercase;
    padding: 3px 10px;
    font-weight: 600;
    border-radius: 2px;
    margin-right: 15px;
    color: #FFF;
    background-color: #212631;
    -webkit-transition: 0.2s opacity;
    transition: 0.2s opacity;
}
.post.post-thumb .post-meta .post-date {
    color: #eceef2;
}
.post-meta .post-date {
    font-size: 13px;
    font-weight: 600;
}
.post.post-thumb .post-title {
    font-size: 22px;
}
.post .post-title {
    font-size: 18px;
    margin-bottom: 0px;
}
.post.post-thumb .post-title > a {
    color: #fff;
    font-size: 22px;
    font-weight: 500;
}
.post.post-thumb .post-title > a:hover {
	text-decoration: none;
}

.post-meta .post-category.cat-1 {
     background-color: #4BB92F;
}
 .post-meta .post-category.cat-2 {
     background-color: #ff8700;
}
 .post-meta .post-category.cat-3 {
     background-color: #8d00ff;
}
 .post-meta .post-category.cat-4 {
     background-color: #0078ff;
}
 .post-meta .post-date {
     font-size: 13px;
     font-weight: 600;
}
 .post .post-title {
     font-size: 18px;
     margin-bottom: 0px;
}
 .post-tags li {
     display:inline-block;
     margin-right:3px;
     margin-bottom:5px;
}
 .post-tags li a {
     display:block;
     color:#fff;
     background-color: #212631;
     padding:3px 10px;
     font-weight:600;
     border-radius:2px;
     -webkit-transition:0.2s opacity;
     transition:0.2s opacity;
}
p{
	font-size: 19px;
	line-height: 2rem;
	margin-top: 2rem;
	margin-bottom: 2rem;
}
</style>
  <!-- Page Content -->
  <div class="container">

	 <div class="row mt-5">

	      <!-- Post Content Column -->
	   	  <div class="col-lg-8">
		        <h1 class="mb-4">{{instance.title}}</h1> 
		        <!-- Preview Image -->
		        <!-- <img class="img-fluid rounded" src="{{instance.referential_image.url}}" alt=""> -->
				<div class="post-content-body">
		              {{ instance.content |safe }}
		        </div>
		        <hr>
	      </div>
	      <!-- /post Content  -->

	  		<div class="col-lg-4">
	  			
	  			<!-- recent post -->
	  			<div class="my-4 ">	
	  					<div class="mb-4">
	  						<h2>أطلع ايضا على</h2>
	  					</div>
						<!-- post1 -->
						<div class="post post-thumb mb-4">
							<a class="post-img" href="{% url 'posts:detail_post' post1.slug%}">
								<img src="{{post1.referential_image.url}}" alt="">
							</a>
							<div class="post-body">
								<div class="post-meta">
									<span class="post-category cat-1">
										{{post1.category}}
									</span>
								</div>
								<h3 class="post-title">
									<a href="{% url 'posts:detail_post' post1.slug %}">
										{{post1.title}}
									</a>
								</h3>
							</div>
						</div>
						<!-- /post1 -->

						<!--post2  -->
						<div class="post post-thumb mb-4">
							<a class="post-img" href="{% url 'posts:detail_post' post2.slug%}">
								<img src="{{post2.referential_image.url}}" alt="">
							</a>
							<div class="post-body">
								<div class="post-meta">
									<a class="post-category cat-1" href="{% url 'posts:category' post2.category %}">
										{{post2.category}}
									</a>
								</div>
								<h3 class="post-title">
									<a href="{% url 'posts:detail_post' post2.slug %}">
										{{post2.title}}
									</a>
								</h3>
							</div>
						</div>
						<!-- /post2 -->
				</div>
				<!-- /recent post -->


				<!-- add some thin new -->
		        <!-- 
		        <div class="card my-4">
		          <h5 class="card-header">Side Widget</h5>
		          <div class="card-body">
		            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
		          </div>
		        </div>
		         -->

	       	</div>
     </div>
    <!-- /.row -->
   </div>
  <!-- /.container -->

{% endblock content %}



 {%block script%}
 <script type="text/javascript">
 	$(document).ready(function(){
 		$(".post-content-body p img").each(function(){
 			$(this).addClass("img-fluid")
 		})

 	})
 </script>	
 {%endblock%}

templates/post_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<style type="text/css">

</style>



<!-- Page Content -->
 <section class="site-section py-5">
      <div class="container">
             <!-- Page Heading -->
           <!--  <h1 class="">قائمة الدروس
            </h1> -->
          <div class="row">
            <div class="col-md-12 col-lg-10">
              {%for bom in posts%}
                <div class="row mb-3">
                    <div class="col-md-5 col-lg-5">
                        {% if bom.category %}
                        {% endif %}
                        <div href="#" class="post-thumb">
                          <h5 class="post-cat-wrap">
                            <span class="post-cat text-white bg-primary">{{ bom.category |upper }}</span>
                          </h5>
                          <div class="post-thumb-overlay-wrap">
                              <img class="img-fluid rounded mb-3 mb-md-0" src="{{bom.referential_image.url}}" alt="">
                          </div>
                        </div>

                    </div>
                    <div class="col-md-7 col-lg-7">
                        <h3>
                           {{ bom.title }}{% if not bom.published %}<small style="color: red"> unpublished{%endif%}</small>
                           {%if bom.timestamp > today %} <small style="color: red">future</small>{%endif%}
                        </h3>
                        <p>{{ bom.description|slice:":100" }} ...</p>
                        <a class="btn btn-primary more-link" style="hover:border: none !important;" href="{% url 'posts:detail_post' bom.slug %}">المزيد !!</a>
                    </div>
                  </div>
                  {% empty %}
        <div class="border p-3 mb-3">
          <h3>لا يوجد تدوينات، إذا كان لديك حساب مسجل من قبل يمكنك <a href="#">تسجيل  الدخول</a>  والقيام بنشر
          أول تدوينة في الموقع.</h3>
      </div>
            {% endfor %}
            <!-- /.row -->
      

      </div>
    </div>
  </div>
</section>

{% include 'pagination.html' with page=posts %}


<!-- end body section -->
{% endblock content %}  

templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- section -->
<div class="section py-5">
	<!-- container -->
	<div class="container">
		<!-- row -->
		<div class="row">
			           <div class="col-md-12 col-lg-10">
            {% if posts %}
              {%for bom in posts%}

                <div class="row mb-3">
                    <div class="col-md-5 col-lg-5">
                        {% if bom.category %}
                        {% endif %}
                        <div href="#" class="post-thumb">
                          <h5 class="post-cat-wrap">
                            <span class="post-cat text-white bg-primary">{{ bom.category |upper }}</span>
                          </h5>
                          <div class="post-thumb-overlay-wrap">
                              <img class="img-fluid rounded mb-3 mb-md-0" src="{{bom.referential_image.url}}" alt="">
                          </div>
                        </div>

                    </div>
                    <div class="col-md-7 col-lg-7">
                        <h3>{{ bom.title }}</h3>
                        <p>{{ bom.description|slice:":100" }} ...</p>
                        <a class="btn btn-primary more-link" style="hover:border: none !important;" href="{% url 'posts:detail_post' bom.slug %}">المزيد !!</a>
                    </div>
                  </div>
            {% endfor %}
            {% else %}
            <h2>No Post Found. Please Search Again!</h2>
			{% endif %}
            <!-- /.row -->
      

      </div>

			<div class="col-md-4">

				<!-- catagories and tags -->
				<!-- /catagories and tags -->

				<!-- archive -->
				<div class="aside-widget">
					<div class="section-title">
						<h2>Archive</h2>
					</div>
					<div class="archive-widget">
						<ul>
							<li><a href="#">Jan 2018</a></li>
							<li><a href="#">Feb 2018</a></li>
							<li><a href="#">Mar 2018</a></li>
						</ul>
					</div>
				</div>
				<!-- /archive -->
			</div>
		</div>
		<!-- /row -->
	</div>
	<!-- /container -->
</div>
<!-- /section -->
{% endblock %}